"""edit user table

Revision ID: 1ac012ba2b39
Revises: 790df4a27014
Create Date: 2024-08-27 12:31:10.371717

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "1ac012ba2b39"
down_revision: Union[str, None] = "790df4a27014"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users", sa.Column("hashed_password", sa.String(), nullable=False)
    )
    op.drop_constraint("uq_users_foo_bar", "users", type_="unique")
    op.drop_column("users", "bar")
    op.drop_column("users", "foo")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column("foo", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    op.add_column(
        "users",
        sa.Column("bar", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    op.create_unique_constraint("uq_users_foo_bar", "users", ["foo", "bar"])
    op.drop_column("users", "hashed_password")
    # ### end Alembic commands ###
