"""create order book association table

Revision ID: 411d8bd864a0
Revises: 0b610d0d40ec
Create Date: 2024-08-29 20:29:23.461080

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "411d8bd864a0"
down_revision: Union[str, None] = "0b610d0d40ec"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "order_book_association",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("order_id", sa.Integer(), nullable=False),
        sa.Column("book_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["book_id"],
            ["books.id"],
            name=op.f("fk_order_book_association_book_id_books"),
        ),
        sa.ForeignKeyConstraint(
            ["order_id"],
            ["orders.id"],
            name=op.f("fk_order_book_association_order_id_orders"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_order_book_association")),
        sa.UniqueConstraint(
            "order_id",
            "book_id",
            name=op.f("uq_order_book_association_order_id_book_id"),
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("order_book_association")
    # ### end Alembic commands ###
